plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
#markdown: kramdown
#markdown: GFM
markdown: kramdown
kramdown:
    math_engine: katex
    
highlighter: rouge
permalink: pretty

#markdown: redcarpet
#redcarpet:
#  extensions:
#    - no_intra_emphasis
#    - fenced_code_blocks
#    - autolink
#    - tables
#    - strikethrough
#    - superscript
#    - with_to_data
    
collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: Galaxy6D

